import {
  Decoration,
  EditorView,
  ViewPlugin,
  WidgetType,
  type DecorationSet,
  type ViewUpdate,
} from "@codemirror/view";
import { visibleLineChunks } from "./visibleLineChunks";

/**
 * Ingestion wraps each extraction in `<!-- orb:extract src="…" -->` … `<!-- /orb:extract -->`
 * so a block can be found and replaced on its own. Markdown renders comments as
 * nothing, but this editor shows raw text, so without help every attachment
 * would grow two lines of machinery. Shown as a slim rule instead — and left as
 * plain text on the line being edited, so it is never hidden from someone
 * deliberately changing it.
 */
const MARKER_RE = /<!-- (\/?)orb:extract(?: src="([^"]*)")? -->/g;

function fileNameFromSrc(src: string): string {
  const last = src.split("/").pop() || src;
  try {
    return decodeURIComponent(last);
  } catch {
    return last;
  }
}

class MarkerWidget extends WidgetType {
  constructor(
    readonly closing: boolean,
    readonly label: string,
  ) {
    super();
  }

  eq(other: MarkerWidget) {
    return other.closing === this.closing && other.label === this.label;
  }

  toDOM() {
    const el = document.createElement("span");
    el.className = this.closing
      ? "cm-extract-marker cm-extract-marker-end"
      : "cm-extract-marker";
    el.setAttribute("contenteditable", "false");
    el.textContent = this.closing ? "" : `extracted from ${this.label}`;
    el.title = this.closing
      ? "End of generated extraction"
      : `Generated by ingestion from ${this.label} — replaced on the next re-ingest`;
    return el;
  }

  ignoreEvent() {
    return true;
  }
}

export function createExtractMarkerDecorations() {
  return ViewPlugin.fromClass(
    class {
      decorations: DecorationSet;

      constructor(view: EditorView) {
        this.decorations = this.build(view);
      }

      update(update: ViewUpdate) {
        if (update.docChanged || update.viewportChanged || update.selectionSet) {
          this.decorations = this.build(update.view);
        }
      }

      build(view: EditorView): DecorationSet {
        const marks: ReturnType<Decoration["range"]>[] = [];
        const activeLine = view.state.doc.lineAt(
          view.state.selection.main.head,
        ).number;

        for (const chunk of visibleLineChunks(view)) {
          MARKER_RE.lastIndex = 0;
          let m: RegExpExecArray | null;
          while ((m = MARKER_RE.exec(chunk.text)) !== null) {
            const from = chunk.offset + m.index;
            const to = from + m[0].length;
            if (view.state.doc.lineAt(from).number === activeLine) continue;
            marks.push(
              Decoration.replace({
                widget: new MarkerWidget(
                  m[1] === "/",
                  m[2] ? fileNameFromSrc(m[2]) : "an attachment",
                ),
              }).range(from, to),
            );
          }
        }
        return Decoration.set(marks, true);
      }
    },
    { decorations: (v) => v.decorations },
  );
}
