import { Decoration, EditorView, WidgetType, type DecorationSet } from "@codemirror/view";
import { StateEffect, StateField, type EditorState } from "@codemirror/state";
import { isAudioUrl, isImageUrl, isVideoUrl, vaultRelPath } from "@/lib/utils";

/**
 * Ingestion wraps each extraction in `<!-- orb:extract src="…" -->` … `<!-- /orb:extract -->`
 * so a block can be found and replaced on its own. Markdown renders comments as
 * nothing, but this editor shows raw text, so without help every attachment
 * would grow pages of machine output. Collapsed by default into one chip
 * ("Transcript from x.m4a · 1,240 words"); expanded, the two markers become
 * slim rules around the visible body. A block holding the cursor never
 * collapses, so nobody loses the line they are editing.
 */
const OPEN_RE = /<!-- orb:extract src="([^"]*)"(?: mode="[a-z]+")? -->/g;
const CLOSE = "<!-- /orb:extract -->";
const MARKER_RE = /<!-- (\/?)orb:extract(?: src="([^"]*)")?(?: mode="[a-z]+")? -->/g;

/** Same identity the backend uses: no query, unquoted, lowercase — and
 * vault-relative, so a marker written as `/vault-files/<kb>/attachments/x`
 * still matches a link stored as `attachments/x`. */
export function extractKey(src: string): string {
  return vaultRelPath((src || "").trim().split("?")[0]).toLowerCase();
}

/** Keys of every attachment that already has a block in this document. */
export function extractedKeys(doc: string): Set<string> {
  const keys = new Set<string>();
  OPEN_RE.lastIndex = 0;
  let m: RegExpExecArray | null;
  while ((m = OPEN_RE.exec(doc)) !== null) keys.add(extractKey(m[1]));
  return keys;
}

/** What a block is, by its attachment's extension. */
export function extractNoun(src: string): "Transcript" | "Description" | "Extracted text" {
  const k = extractKey(src);
  if (isVideoUrl(k) || isAudioUrl(k)) return "Transcript";
  if (isImageUrl(k)) return "Description";
  return "Extracted text";
}

function fileNameFromSrc(src: string): string {
  const last = src.split("/").pop() || src;
  try {
    return decodeURIComponent(last);
  } catch {
    return last;
  }
}

export const toggleExtractEffect = StateEffect.define<string>();

/** Keys of blocks the user has opened. */
export const expandedExtracts = StateField.define<Set<string>>({
  create: () => new Set(),
  update(value, tr) {
    let next = value;
    for (const e of tr.effects) {
      if (e.is(toggleExtractEffect)) {
        next = new Set(next);
        if (next.has(e.value)) next.delete(e.value);
        else next.add(e.value);
      }
    }
    return next;
  },
});

export function toggleExtractBlock(view: EditorView, rawSrc: string) {
  view.dispatch({ effects: toggleExtractEffect.of(extractKey(rawSrc)) });
}

class CollapsedWidget extends WidgetType {
  constructor(
    readonly key: string,
    readonly label: string,
  ) {
    super();
  }

  eq(other: CollapsedWidget) {
    return other.key === this.key && other.label === this.label;
  }

  toDOM(view: EditorView) {
    const el = document.createElement("div");
    el.className = "cm-extract-collapsed";
    el.setAttribute("contenteditable", "false");
    el.title = "Generated by Orb — click to show. Replaced when this attachment is processed again.";
    el.textContent = `${this.label} ▸`;
    el.addEventListener("mousedown", (e) => {
      e.preventDefault();
      view.dispatch({ effects: toggleExtractEffect.of(this.key) });
    });
    return el;
  }

  ignoreEvent() {
    return true;
  }
}

class MarkerWidget extends WidgetType {
  constructor(
    readonly closing: boolean,
    readonly label: string,
    readonly key: string,
  ) {
    super();
  }

  eq(other: MarkerWidget) {
    return other.closing === this.closing && other.label === this.label && other.key === this.key;
  }

  toDOM(view: EditorView) {
    const el = document.createElement("span");
    el.className = this.closing
      ? "cm-extract-marker cm-extract-marker-end"
      : "cm-extract-marker";
    el.setAttribute("contenteditable", "false");
    el.textContent = this.closing ? "" : `${this.label} ▾`;
    el.title = this.closing
      ? "End of generated extraction"
      : "Generated by Orb from this attachment — click to hide";
    if (!this.closing) {
      el.addEventListener("mousedown", (e) => {
        e.preventDefault();
        view.dispatch({ effects: toggleExtractEffect.of(this.key) });
      });
    }
    return el;
  }

  ignoreEvent() {
    return true;
  }
}

type Block = { from: number; to: number; src: string; key: string; words: number };

// ponytail: re-scans the whole document text on every selection change.
// Notes are kilobytes; index blocks incrementally if a vault note ever isn't.
function findBlocks(doc: string): Block[] {
  const blocks: Block[] = [];
  OPEN_RE.lastIndex = 0;
  let m: RegExpExecArray | null;
  while ((m = OPEN_RE.exec(doc)) !== null) {
    const end = doc.indexOf(CLOSE, m.index + m[0].length);
    if (end === -1) break;
    const body = doc.slice(m.index + m[0].length, end);
    blocks.push({
      from: m.index,
      to: end + CLOSE.length,
      src: m[1],
      key: extractKey(m[1]),
      words: body.split(/\s+/).filter(Boolean).length,
    });
    OPEN_RE.lastIndex = end + CLOSE.length;
  }
  return blocks;
}

function buildDecorations(state: EditorState): DecorationSet {
  const text = state.doc.toString();
  const blocks = findBlocks(text);
  if (blocks.length === 0) return Decoration.none;
  const expanded = state.field(expandedExtracts);
  const marks: ReturnType<Decoration["range"]>[] = [];
  const ranges = state.selection.ranges;
  const activeLine = state.doc.lineAt(state.selection.main.head).number;

  for (const b of blocks) {
    const fromLine = state.doc.lineAt(b.from);
    const toLine = state.doc.lineAt(b.to);
    const cursorInside = ranges.some((r) => r.to >= fromLine.from && r.from <= toLine.to);
    const label = `${extractNoun(b.src)} from ${fileNameFromSrc(b.src)} · ${b.words.toLocaleString()} words`;

    if (!expanded.has(b.key) && !cursorInside) {
      marks.push(
        Decoration.replace({ widget: new CollapsedWidget(b.key, label), block: true }).range(
          fromLine.from,
          toLine.to,
        ),
      );
      continue;
    }

    // Expanded: the two comment markers become rules, except on the line being edited.
    MARKER_RE.lastIndex = b.from;
    let m: RegExpExecArray | null;
    while ((m = MARKER_RE.exec(text)) !== null && m.index < b.to) {
      const from = m.index;
      const to = from + m[0].length;
      if (state.doc.lineAt(from).number === activeLine) continue;
      marks.push(
        Decoration.replace({
          widget: new MarkerWidget(m[1] === "/", label, b.key),
        }).range(from, to),
      );
    }
  }
  return Decoration.set(marks, true);
}

const extractDecorations = StateField.define<DecorationSet>({
  create: buildDecorations,
  update(value, tr) {
    if (tr.docChanged || tr.selection || tr.effects.some((e) => e.is(toggleExtractEffect))) {
      return buildDecorations(tr.state);
    }
    return value;
  },
  provide: (f) => EditorView.decorations.from(f),
});

// Block-level replacements must come from state, not a view plugin — plugins
// run after the viewport is measured and may not change vertical layout.
export function createExtractMarkerDecorations() {
  return [expandedExtracts, extractDecorations];
}
